OnlineRestaurant.Web/Areas/Admin/Controllers/DishController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineRestaurant.DataAccess.Repository.IRepository;
using OnlineRestaurant.Models;
using OnlineRestaurant.Models.ViewModels;
using OnlineRestaurant.Utility;

namespace OnlineRestaurant.Web.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles=Constants.RoleAdmin)]
public class DishController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    
    public DishController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var model = await _unitOfWork.Dishes.GetAllAsync(includedProperties:"Category");
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var categories = await _unitOfWork.Categories.GetAllAsync();

        if (categories is null)
            throw new Exception("Categories mustn't be null");
        
        var dishVm = new DishViewModel
        {
            Categories = categories.Select(i => new SelectListItem
            {
                Text = i.Title,
                Value = i.Id.ToString()
            }),
            Dish = new ()
        };
        return View(dishVm);
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(DishViewModel model, List<IFormFile>? files)
    {
        await NameValidation(model.Dish);
        
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        model.Dish.CreationDate = DateTime.UtcNow;

        await _unitOfWork.Dishes.AddAsync(model.Dish);
        
        await _unitOfWork.SaveChangesAsync();

        if (files is not null)
            await WriteImagesToDbAsync(files, model.Dish.Id);
        
        await _unitOfWork.SaveChangesAsync();
        
        TempData["success"] = "Dish created successfully";
        return RedirectToAction(nameof(Index));
    }

    private async Task WriteImagesToDbAsync(List<IFormFile> files, int id)
    {
        foreach (var file in files)
        {
            using var memoryStream = new MemoryStream();
            await file.CopyToAsync(memoryStream);
            var imageInBytes = memoryStream.ToArray();
            await _unitOfWork.DishImages.AddAsync(new DishImageModel
            {
                CreationDate = DateTime.UtcNow,
                Image = imageInBytes,
                DishId = id,
            });
        }
    }

    private async Task NameValidation(DishModel model, int id = 0)
    {
        var name = model.Name.ToLower();
        if (id != 0)
        {
            var dish = await _unitOfWork.Dishes.GetByIdAsync(id);
            if (dish is not null && dish.Name == model.Name)
                return;
        }
        
        var dishes = await _unitOfWork.Dishes.GetAllAsync();
        
        if (dishes is not null)
        {
            foreach (var dish in dishes)
            {
                if (name == dish.Name.ToLower())
                {
                    ModelState.AddModelError(nameof(DishModel.Name), "This name already exists!");
                    return;
                }
            }
        }
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id is null or 0)
            return NotFound();
        
        var categories = await _unitOfWork.Categories.GetAllAsync();

        if (categories is null)
            throw new Exception($"Categories mustn't be null");
        
        var dishVm = new DishViewModel
        {
            Categories = categories.Select(i => new SelectListItem
            {
                Text = i.Title,
                Value = i.Id.ToString()
            }),
            Dish = (await _unitOfWork.Dishes.GetByIdAsync(id.Value))!
        };
        
        return View(dishVm);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(DishViewModel model)
    {
        await NameValidation(model.Dish, model.Dish.Id);

        if (!ModelState.IsValid)
            return View(model);
        
        model.Dish.CreationDate = model.Dish.CreationDate.ToUniversalTime();
        await _unitOfWork.Dishes.UpdateAsync(model.Dish);
        await _unitOfWork.SaveChangesAsync();

        TempData["success"] = "Category updated successfully";

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int? id)
    {
        if (id is null or 0)
            return NotFound();
        
        var dish = await _unitOfWork.Dishes.GetByIdAsync(id.Value);
        if (dish == null)
            return NotFound();
        
        await _unitOfWork.Dishes.DeleteAsync(dish);
        await _unitOfWork.DishImages.DeleteAsync(await _unitOfWork.DishImages.GetAsync(i => i.DishId == dish.Id)?? throw new ArgumentNullException());
        await _unitOfWork.SaveChangesAsync();

        return Json(new { success = true, message = "Dish deleted successfully" });
    }
}

OnlineRestaurant.Web/Controllers/DishController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineRestaurant.DataAccess.Repository.IRepository;
using OnlineRestaurant.Models;
using OnlineRestaurant.Models.ViewModels;

namespace OnlineRestaurant.Web.Controllers;

public class DishController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    
    public DishController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var model = await _unitOfWork.Dishes.GetAllAsync(includedProperties:"Category");
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var categories = await _unitOfWork.Categories.GetAllAsync();

        if (categories is null)
            throw new Exception("Categories mustn't be null");
        
        var dishVm = new DishViewModel
        {
            Categories = categories.Select(i => new SelectListItem
            {
                Text = i.Title,
                Value = i.Id.ToString()
            }),
            Dish = new ()
        };
        return View(dishVm);
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(DishViewModel model, List<IFormFile>? files)
    {
        await NameValidation(model.Dish);
        
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        model.Dish.CreationDate = DateTime.UtcNow;

        await _unitOfWork.Dishes.AddAsync(model.Dish);
        
        await _unitOfWork.SaveChangesAsync();

        if (files is not null)
            await WriteImagesToDbAsync(files, model.Dish.Id);
        
        await _unitOfWork.SaveChangesAsync();
        
        TempData["success"] = "Dish created successfully";
        return RedirectToAction("Index");
    }

    private async Task WriteImagesToDbAsync(List<IFormFile> files, int id)
    {
        foreach (var file in files)
        {
            using var memoryStream = new MemoryStream();
            await file.CopyToAsync(memoryStream);
            var imageInBytes = memoryStream.ToArray();
            await _unitOfWork.DishImages.AddAsync(new DishImageModel
            {
                CreationDate = DateTime.UtcNow,
                Image = imageInBytes,
                DishId = id,
            });
        }
    }

    private async Task NameValidation(DishModel model, int id = 0)
    {
        var name = model.Name.ToLower();
        if (id != 0)
        {
            var dish = await _unitOfWork.Dishes.GetByIdAsync(id);
            if (dish is not null && dish.Name == model.Name)
                return;
        }
        
        var dishes = await _unitOfWork.Dishes.GetAllAsync();
        
        if (dishes is not null)
        {
            foreach (var dish in dishes)
            {
                if (name == dish.Name.ToLower())
                {
                    ModelState.AddModelError(nameof(DishModel.Name), "This name already exists!");
                    return;
                }
            }
        }
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id is null or 0)
            return NotFound();
        
        var categories = await _unitOfWork.Categories.GetAllAsync();

        if (categories is null)
            throw new Exception($"Categories mustn't be null");
        
        var dishVm = new DishViewModel
        {
            Categories = categories.Select(i => new SelectListItem
            {
                Text = i.Title,
                Value = i.Id.ToString()
            }),
            Dish = (await _unitOfWork.Dishes.GetByIdAsync(id.Value))!
        };
        
        return View(dishVm);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(DishViewModel model)
    {
        await NameValidation(model.Dish, model.Dish.Id);

        if (!ModelState.IsValid)
            return View(model);
        
        model.Dish.CreationDate = model.Dish.CreationDate.ToUniversalTime();
        await _unitOfWork.Dishes.UpdateAsync(model.Dish);
        await _unitOfWork.SaveChangesAsync();

        TempData["success"] = "Category updated successfully";

        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id is null or 0)
            return NotFound();

        var dish = await _unitOfWork.Dishes.GetByIdAsync(id.Value);

        if (dish == null)
            return NotFound();

        return View(dish);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int? id)
    {
        var dish = await _unitOfWork.Categories.GetAsync(x => x.Id == id);
        if (dish == null)
            return NotFound();

        await _unitOfWork.Categories.DeleteAsync(dish);
        await _unitOfWork.SaveChangesAsync();
        
        TempData["success"] = "Category deleted successfully";
        
        return RedirectToAction("Index");
    }
}

OnlineRestaurant.Web/Areas/Admin/Views/Dish/Create.cshtml
@model DishViewModel

<div class="container w-50">
    <form method="post" enctype="multipart/form-data" multiple>
        <input asp-for="Dish.Id" hidden/>
        <div class="p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-success pb-3 text-center">Add new dish</h2>
            </div>
            <div class="row mb-2 p-1">
                <label asp-for="Dish.Name" class="p-0"></label>
                <input asp-for="Dish.Name" class="form-control"/>
                <span asp-validation-for="Dish.Name" class="text-danger"></span>
            </div>

            <div class="row mb-2 p-1">
                <label asp-for="Dish.Description" class="p-0"></label>
                <input asp-for="Dish.Description" class="form-control"/> 
                <span asp-validation-for="Dish.Description" class="text-danger"></span>
            </div>

            <div class="row mb-2 p-1">
                <label asp-for="Dish.Price" class="p-0"></label>
                <input asp-for="Dish.Price" class="form-control"/>
                <span asp-validation-for="Dish.Price" class="text-danger"></span>
            </div>

            <div class="row mb-2 p-1">
                <label class="p-0">Choose category</label>
                <select asp-for="@Model.Dish.CategoryId" asp-items="@Model.Categories" class="form-select border-0 shadow">
                    <option disabled selected>--Select Category--</option>
                </select>
                <span asp-validation-for="Dish.CategoryId" class="text-danger"></span>
            </div>
            
            <div class="row mb-2 p-1">
                <label class="p-0">Add pictures</label>
                <input type="file" name="files" class="form-control border-0 shadow"/>
            </div>
            
            <div class="row d-flex justify-content-center">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary form-control">Create</button>
                </div>
                <div class="col-6 col-md-3">
                    <a class="btn btn-outline-secondary form-control" asp-controller="Dish" asp-action="Index">Back</a>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

OnlineRestaurant.Web/Areas/Admin/Views/Dish/Edit.cshtml
@model DishViewModel

<div class="container w-50">
    <form method="post">
        <input asp-for="Dish.Id" hidden/>
        <div class="p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-success pb-3 text-center">Edit dish</h2>
            </div>
            <div class="row mb-2 p-1">
                <label asp-for="Dish.Name" class="p-0"></label>
                <input asp-for="Dish.Name" class="form-control"/>
                <span asp-validation-for="Dish.Name" class="text-danger"></span>
            </div>

            <div class="row mb-2 p-1">
                <label asp-for="Dish.Description" class="p-0"></label>
                <input asp-for="Dish.Description" class="form-control"/>
                <span asp-validation-for="Dish.Description" class="text-danger"></span>
            </div>

            <div class="row mb-2 p-1">
                <label asp-for="Dish.Price" class="p-0"></label>
                <input asp-for="Dish.Price" class="form-control"/>
                <span asp-validation-for="Dish.Price" class="text-danger"></span>
            </div>

            <div class="row mb-2 p-1">
                <label class="p-0">Choose category</label>
                <select asp-for="@Model.Dish.CategoryId" asp-items="@Model.Categories" class="form-select border-0 shadow">
                    <option disabled selected>--Select Category--</option>
                </select>
                <span asp-validation-for="Dish.CategoryId" class="text-danger"></span>
            </div>

            <div class="row mb-2 p-1">
                <label class="p-0">Add pictures</label>
                <input type="file" name="files" class="form-control border-0 shadow"/>
            </div>

            <div class="row d-flex justify-content-center">
                <div class="col-6 col-md-3 align-content-md-center">
                    <button type="submit" class="btn btn-warning form-control">Update</button>
                </div>
                <div class="col-6 col-md-3">
                    <a class="btn btn-outline-light form-control" asp-action="Index">Back</a>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

OnlineRestaurant.Web/Areas/Admin/Views/Dish/Index.cshtml
@model List<DishModel>

<div class="container w-50">
    <input name="id" hidden />
    <div class="d-flex justify-content-center">
        <div>
            <h2 class="text-success">Dishes List</h2>
        </div>

    </div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Dish Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Category</th>
            <th></th>
        </tr>
        </thead>

        <tbody>
        @foreach (var elem in Model.OrderBy(i => i.Id))
        {
            <tr>
                <td>@elem.Name</td>
                <td>@elem.Description</td>
                <td>@elem.Price</td>
                <th>@elem.Category.Title</th>
                <td>
                    <div class="d-flex justify-content-end">
                        <a asp-controller="Dish" asp-action="Edit" asp-route-id="@elem.Id" class="btn btn-primary m-1"><i class="bi bi-pencil"></i></a>
                        <a onclick="Delete('/admin/dishes/delete/@elem.Id')" class="btn btn-danger m-1"><i class="bi bi-trash"></i></a>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <div class="d-flex justify-content-center mt-1">
        <div>
            <a asp-controller="Dish" asp-action="Create" class="btn btn-outline-success"><i class="bi bi-plus-circle"></i> Add dish</a>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/js/site.js"></script>
}